/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Charity;

import Business.Enterprise.CharityEnterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author kathe
 */
public class AidWorkerWorkAreaJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    private UserAccount userAccount;
    private CharityEnterprise charity;
    /**
     * Creates new form AidWorkerWorkAreaJPanel
     */
    public AidWorkerWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount,CharityEnterprise charity) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userAccount=userAccount;
        this.charity=charity;
        valueLabel.setText(charity.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        assignJButton = new javax.swing.JButton();
        processJButton = new javax.swing.JButton();
        viewWorkEvaluationJButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(180, 224, 201));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        valueLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 158, 26));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Aid Worker Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 300, 39));

        assignJButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        assignJButton.setText("Assign Work Requests");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });
        add(assignJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 260, -1));

        processJButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        processJButton.setText("Process Work Requests");
        processJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJButtonActionPerformed(evt);
            }
        });
        add(processJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 260, -1));

        viewWorkEvaluationJButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        viewWorkEvaluationJButton.setText("View Demend Evaluation");
        viewWorkEvaluationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewWorkEvaluationJButtonActionPerformed(evt);
            }
        });
        add(viewWorkEvaluationJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 260, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Enterprise:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\NEU_Study\\INFO 5100 Spring\\Final_Project_Zeta\\Zeta_Images\\COVIDweb_02_bed.png")); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 210, 210));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\NEU_Study\\INFO 5100 Spring\\Final_Project_Zeta\\Zeta_Images\\COVIDweb_04_CallDoc.png")); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 210, 210));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\NEU_Study\\INFO 5100 Spring\\Final_Project_Zeta\\Zeta_Images\\COVIDweb_05_mask.png")); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed
        // TODO add your handling code here:
        AssignWorkRequestsJPanel assignWorkRequestsJPanel=new AssignWorkRequestsJPanel(userProcessContainer,userAccount,charity);
        userProcessContainer.add("AssignWorkRequestsJPanel",assignWorkRequestsJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_assignJButtonActionPerformed

    private void processJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJButtonActionPerformed
        // TODO add your handling code here:
        ProcessWorkRequestsJPanel processWorkRequestsJPanel=new ProcessWorkRequestsJPanel(userProcessContainer,userAccount,charity);
        userProcessContainer.add("userProcessContainer",processWorkRequestsJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_processJButtonActionPerformed

    private void viewWorkEvaluationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewWorkEvaluationJButtonActionPerformed
        // TODO add your handling code here:
        ViewWorkEvaluationJPanel viewWorkEvaluationJPanel=new ViewWorkEvaluationJPanel(userProcessContainer,userAccount,charity);
        userProcessContainer.add("userProcessContainer",viewWorkEvaluationJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewWorkEvaluationJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton processJButton;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JButton viewWorkEvaluationJButton;
    // End of variables declaration//GEN-END:variables
}
