/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Charity;

import Business.Enterprise.CharityEnterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DonorWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lgfx0
 */
public class ProcessDonationJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount useraccount;
    private CharityEnterprise charity;
    private int sum=0;
    /**
     * Creates new form ProcessDonationJPanel
     */
    public ProcessDonationJPanel(JPanel userProcessContainer,UserAccount useraccount,CharityEnterprise charity) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.useraccount= useraccount;
        this.charity=charity;
        
        populateTable();
        sumJLabel.setText(Integer.toString(sum));
    }

    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)donationJTable.getModel();
        model.setRowCount(0);
        sum =0;
        for(WorkRequest request: charity.getWorkQueue().getWorkRequestList()){
            if(request.getClass().getName().contains("VolunteerWorkRequest")){
                continue;
            }else if(request.getClass().getName().contains("HospitalWorkRequest")){
                continue;
            }
            DonorWorkRequest drequest = (DonorWorkRequest)request;
            Object[]row=new Object[5];
            row[0]= drequest.getRequestId();
            row[1]= drequest.getReceiver()==null?null:drequest.getReceiver().getPerson().getName();
            row[2]= drequest.getSender();
            row[3]= drequest.getDonor().getQuantity();
            row[4]= drequest.getStatus();
           
            if(drequest.getStatus().equals("Received")){
                sum+= drequest.getDonor().getQuantity();
            }
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        donationJTable = new javax.swing.JTable();
        processJButton = new javax.swing.JButton();
        sumJLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(209, 231, 233));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        backJButton.setText("<<back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        donationJTable.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        donationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Receiver", "Donor Name", "Money ", "Status"
            }
        ));
        donationJTable.setRowHeight(30);
        jScrollPane1.setViewportView(donationJTable);
        if (donationJTable.getColumnModel().getColumnCount() > 0) {
            donationJTable.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 750, 140));

        processJButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        processJButton.setText("Process");
        processJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJButtonActionPerformed(evt);
            }
        });
        add(processJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        sumJLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        add(sumJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 140, 21));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Sum of Donation:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 190, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\NEU_Study\\INFO 5100 Spring\\Final_Project_Zeta\\Zeta_Images\\receive money2.gif")); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 440, 370));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void processJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow =donationJTable.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select at least a row.", "INFORMATION", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Integer wrSelectedRow=(Integer)donationJTable.getValueAt(selectedRow, 0);
        
        DonorWorkRequest drequest=null;
         for(WorkRequest request:charity.getWorkQueue().getWorkRequestList()){
            if(request.getClass().getName().contains("VolunteerWorkRequest")){
                continue;
            }else if(request.getClass().getName().contains("HospitalWorkRequest")){
                continue;
            }
            DonorWorkRequest newrequest=(DonorWorkRequest)request;
            if(wrSelectedRow.equals(newrequest.getRequestId())){
                drequest=newrequest;
                break;
            }
        }
        if(drequest!=null){
            if(drequest.getReceiver()!=null){
                JOptionPane.showMessageDialog(this, "You can't process twice!", "INFORMATION", JOptionPane.ERROR_MESSAGE);
                return;
            }
            drequest.setReceiver(useraccount);
            drequest.setStatus("Received");
        }
        
        
        
       populateTable();
       sumJLabel.setText(Integer.toString(sum));
    }//GEN-LAST:event_processJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTable donationJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton processJButton;
    private javax.swing.JLabel sumJLabel;
    // End of variables declaration//GEN-END:variables
}
